### ISSUE TITLE
Running npm run dev throwing an exception

### ISSUE THREAD

**Issue by ashmanmalik** [chargetrip/developers#216]
While run npm run dev command is throwing this below exception

`Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file coroutine.cc, line 134.
Abort trap: 6
An0nym0usRoot3xDr:devhub ashmanmalik$ node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 76385.
    at /Users/ashman/developer/devhub/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}`

Can anyone please helps in this? Thanks in advance

**Comment by Wouter125** [comment]
Part of our `npm run dev` flow runs certain private scripts. You need to take those out and only run the bare minimum locally. This project is mostly open-sourced to open PRs on our MD files.
